stages:
  data-ingestion:
    cmd: python components/dataIngestion.py
    deps: 
    - components/dataIngestion.py
    outs: 
    - data/raw
    params:
    - data-ingestion.test_size
    - data-ingestion.random_state
  
  data-preprocessing:
    cmd: python components/dataPreprocessing.py
    deps:
    - data/raw
    - components/dataPreprocessing.py
    outs: 
    - data/interim
  
  feature-engineering:
    cmd: python components/featureEngineering.py
    deps:
    - data/interim
    - components/featureEngineering.py
    outs: 
    - data/processed
    params:
    - feature-engineering.limit
  
  model-training:
    cmd: python components/modelTraining.py
    deps:
    - data/processed
    - components/modelTraining.py
    outs: 
    - models/random_forest_model.pkl
    params:
    - model-training.n_estimators
    - model-training.random_state
  
  model-evaluation:
    cmd: python  components/modelEvaluation.py
    deps:
    - models/
    - components/modelEvaluation.py
    outs: 
    - reports/metrics.json